name: Build, Push and Deploy

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-secret:${{ github.sha }}
          platforms: linux/amd64

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to remote server (SSH)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT || 22 }}
          script: |
            set -e
            echo "Logging into Docker Hub and pulling image..."
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/node-secret:${{ github.sha }}
            docker pull $IMAGE
            docker stop node_secret || true
            docker rm node_secret || true
            docker run -d --name node_secret --restart=always -p 80:3000 \
              -e SECRET_MESSAGE='${{ secrets.SECRET_MESSAGE }}' \
              -e USERNAME='${{ secrets.APP_USERNAME }}' \
              -e PASSWORD='${{ secrets.APP_PASSWORD }}' \
              $IMAGE
